name: Build and Deploy
on: 
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: yarn install && yarn vuepress:build
        BUILD_DIR: docs/.vuepress/dist/